### ISSUE TITLE
Could not find zendesk.messaging:messaging-android:2.13.0 for building APK file.

### ISSUE THREAD

**Issue by hamedfoodready** [leegeunhyeok/react-native-zendesk-messaging#37]
**Describe the bug**
We have a expo dev-client application, I have installed the package and it works, but recently for android it is failing with the following issue:
Could not find zendesk.messaging:messaging-android:2.13.0

**To Reproduce**
1. try to build app with the installed react-native-zendesk-messaging

**Expected behavior**
execute build successfully

**Screenshots**
<img width="1149" alt="Screenshot 2024-02-07 at 9 35 42 PM" src="https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/127131884/cf2c3743-ba10-4d72-84b0-6ee7098d2855">

**Environment (please complete the following information):**
 - Platform: [Android]
 - React Native Version : "0.71.14"
 - Zendesk SDK Version : 0.2.1

**Additional context**
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find zendesk.messaging:messaging-android:2.13.0.
     Searched in the following locations:
       - http://10.4.0.201:8081/artifactory/libs-release/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
       - file:/home/expo/workingdir/build/node_modules/react-native/android/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
       - file:/home/expo/workingdir/build/node_modules/jsc-android/dist/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
       - https://dl.google.com/dl/android/maven2/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
       - https://repo.maven.apache.org/maven2/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
       - https://www.jitpack.io/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/zendesk/messaging/messaging-android/2.13.0/messaging-android-2.13.0.pom
     Required by:
         project :app > project :react-native-zendesk-messaging

**Comment by leegeunhyeok** [comment]
Did you add repository configuration to your build.gradle?

https://github.com/leegeunhyeok/react-native-zendesk-messaging/blob/master/docs/getting-started.md#android

**Comment by hamedfoodready** [comment]
Yes, I did that.

**Comment by hamedfoodready** [comment]
Also the repo has been changed from, 'https://zendesk.jfrog.io/artifactory/repo' changed to "https://zendesk.jfrog.io/ui/native/repo". 

is there any special java version configuration fir parsing POM file?

**Comment by hamedfoodready** [comment]
I have tested all possible things but its so weird for me that event i used patch-package and changed the repo URL but another issue showing related to Parsing POM file is not well-formed! even i have updated to latest version.

Could not resolve zendesk.messaging:messaging-android:2.8.0.
     Required by:
         project :react-native-messaging-zendesk
      > Could not resolve zendesk.messaging:messaging-android:2.8.0.
         > Could not parse POM https://zendesk.jfrog.io/ui/native/repo/zendesk/messaging/messaging-android/2.8.0/messaging-android-2.8.0.pom
            > The markup in the document preceding the root element must be well-formed.
            
            
<img width="1141" alt="Screenshot 2024-02-09 at 10 49 47 AM" src="https://github.com/leegeunhyeok/react-native-zendesk-messaging/assets/127131884/cb9c6626-b204-4147-b3d0-3a31e8ae488d">

**Comment by sashamykhalchuk93** [comment]
It looks like ` "build:ios:dev": "eas build -p ios -e development --local",` ignore `android/build.gradle`, because any changes in this file not reflected on build

**Comment by hamedfoodready** [comment]
> I have the same error. It looks like ` "build:android:dev": "eas build -p android -e development --local",` ignore `android/build.gradle`, because any changes in this file not reflected on build If run `expo run:android` - ok

our app is built on eas servers, so what can i do to resolve the build issue?

**Comment by sashamykhalchuk93** [comment]
> > I have the same error. It looks like ` "build:android:dev": "eas build -p android -e development --local",` ignore `android/build.gradle`, because any changes in this file not reflected on build If run `expo run:android` - ok
> 
> our app is built on eas servers, so what can i do to resolve the build issue?

I added plugin to my app.config.json.
Now this plugin run for each build and check if /android/build.gradle has this repositories 

withAndroidGradlePlugin.js
`const { withProjectBuildGradle } = require('@expo/config-plugins')
const {
  createGeneratedHeaderComment,
  removeGeneratedContents,
} = require('@expo/config-plugins/build/utils/generateCode')

// Because we need the package to be added AFTER the React and Google maven packages, we create a new allprojects.
// It's ok to have multiple allprojects.repositories, so we create a new one since it's cheaper than tokenizing
// the existing block to find the correct place to insert our camera maven.
const gradleMaven = `allprojects { repositories { maven { url 'https://zendesk.jfrog.io/artifactory/repo' } } }`

const withAndroidGradle = _config => {
  return withProjectBuildGradle(_config, config => {
    if (config.modResults.language === 'groovy') {
      config.modResults.contents = addZendeskImport(config.modResults.contents).contents
    } else {
      throw new Error('Cannot add camera maven gradle because the build.gradle is not groovy')
    }
    return config
  })
}

function addZendeskImport(src) {
  return appendContents({
    tag: 'zendesk-messaging',
    src,
    newSrc: gradleMaven,
    comment: '//',
  })
}

// Fork of config-plugins mergeContents, but appends the contents to the end of the file.
function appendContents({ src, newSrc, tag, comment }) {
  const header = createGeneratedHeaderComment(newSrc, tag, comment)
  if (!src.includes(header)) {
    // Ensure the old generated contents are removed.
    const sanitizedTarget = removeGeneratedContents(src, tag)
    const contentsToAdd = [
      // @something
      header,
      // contents
      newSrc,
      // @end
      `${comment} @generated end ${tag} \n`,
    ].join('\n')

    return {
      contents: sanitizedTarget ?? src + contentsToAdd,
      didMerge: true,
      didClear: !!sanitizedTarget,
    }
  }
  return { contents: src, didClear: false, didMerge: false }
}
// TODO: add params like maven array and make this plugin reuseable for others maven
const withAndroidGradlePlugin = config => {
  return withAndroidGradle(config)
}

module.exports = withAndroidGradlePlugin
`
